name: Pages

on:
  push:
    branches: [main]
    paths:
      - src/**

jobs:
  docs:
    runs-on: ubuntu-24.04
    container: ghcr.io/cpp-review-dune/introductory-review/aur

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v16
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: latex.yml
          name: PDF-artifact

      - name: "Untar files"
        run: |
          tar -I zstd -xvf PDF.tar.zst
          mkdir -p docs
          mv public/*.pdf docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true
          publish_branch: gh-pages
